//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMessage
    {
        public int Log_ID { get; set; }
        public string Log_Name { get; set; }
        public string Log_Message { get; set; }
        public string AttachShow1 { get; set; }
        public string AttachFile { get; set; }
        public DateTime CreateDate { get; set; }
        public int  CreateBy { get; set; }
        public int Recive { get; set; }
        public int Message_ID { get; set; }
    }
}
