//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public int UserID { get; set; }
        public int ProjectID { get; set; }
        public int Role { get; set; }
        public int MemberID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
