//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public System.Guid Role_ID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Initial { get; set; }
        public string Role_Detail { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
