//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIT()
        {
            this.SITSteps = new HashSet<SITStep>();
        }
    
        public int SIT_ID { get; set; }
        public int Project_ID { get; set; }
        public int Tester_ID { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string AttachShow { get; set; }
        public string AttachFile { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public int CreateBy { get; set; }
        public int UpdateBy { get; set; }
        public int Dev_ID { get; set; }
        public DateTime Send_Date_T { get; set; }
        public DateTime Send_Date_Q { get; set; }
        public int Status { get; set; }
        public string Commnet_Test { get; set; }
        public string Comment_Dev { get; set; }
        public string Comment_QA { get; set; }
        public string Comment_CM { get; set; }
        public int QA_ID { get; set; }
        public int Handle { get; set; }
        public int Defect_SIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SITStep> SITSteps { get; set; }
    }
}
