//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTaskSubmisstion
    {
        public int Submit_ID { get; set; }
        public DateTime AssignDate { get; set; }
        public DateTime Deadline { get; set; }
        public DateTime SubmitDate { get; set; }
        public int HandleBy { get; set; }
        public int SubID { get; set; }
    
        public virtual SubTask SubTask { get; set; }
    }
}
