//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.SubTasks = new HashSet<SubTask>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public double TotalPercent { get; set; }
        public Nullable<int> Task_level { get; set; }
        public string DescriptionTest { get; set; }
        public int TestID { get; set; }
        public System.DateTime TestSentDate { get; set; }
        public byte TestStatus { get; set; }
        public string DescriptionQA { get; set; }
        public Nullable<int> QAID { get; set; }
        public System.DateTime QASentDate { get; set; }
        public byte QAStatus { get; set; }
        public string AttachShow { get; set; }
        public string AttachFile { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int ProjectID { get; set; }
        public int CreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTask> SubTasks { get; set; }
    }
}
