//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Users_ID { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public string User_Name { get; set; }
        public string User_LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public string ContractFrom { get; set; }
        public System.DateTime Date_of_Started { get; set; }
        public Nullable<System.DateTime> Date_of_Ended { get; set; }
        public string AttachShow1 { get; set; }
        public string AttachShow2 { get; set; }
        public string AttachShow3 { get; set; }
        public string AttachShow4 { get; set; }
        public string AttachFile1 { get; set; }
        public string AttachFile2 { get; set; }
        public string AttachFile3 { get; set; }
        public string AttachFile4 { get; set; }
        public string Skills { get; set; }
        public Nullable<double> SuccPass { get; set; }
        public Nullable<double> Non_Success { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string RoleID { get; set; }
        public string ContractID { get; set; }
        public string PositionID { get; set; }
        public bool Favorite { get; set; }
    }
}
